# Site settings
title: Anna Gierczyk Logopeda Wrocław
email: anna@logowroclaw.pl
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner: Anna Gierczyk
email: anna@logowroclaw.pl
facebook_username: logowroclaw
twitter_username: logowroclaw
googleplus_username: 112877606998106647995
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone: +48 880 062 407
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown
